name: 08 - Runners

on:
  workflow_dispatch:

jobs:
  linux-job:
    runs-on: ubuntu-latest

    steps:
      - name: Test output
        run: |
          echo "================================"
          echo "Hello from GitHub Actions!"
          echo "================================"
          echo "OS       = $RUNNER_OS"
          echo "ARCH     = $RUNNER_ARCH"
          echo "HOME     = $HOME"
          echo "TEMP     = $RUNNER_TEMP"
          echo "WORKSPACE = $GITHUB_WORKSPACE"
          echo "================================"
